services:
  - type: web
    name: food-insecurity-api
    runtime: python
    plan: free
    region: ohio
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: GEMINI_API_KEY
        sync: false
      - key: EARTHDATA_TOKEN
        sync: false

staticSites:
  - name: rootbridge-frontend
    branch: main
    rootDir: rootbridge-project
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    pullRequestPreviewsEnabled: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
